In [1]:
from sklearn.linear_model import Ridge
import numpy as np
import pandas as pd
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.linear_model import LassoCV, LassoLarsCV, LassoLarsIC

In [2]:
n_samples, n_features = 10, 5
rng = np.random.RandomState()
y = rng.randn(n_samples)
X = rng.randn(n_samples, n_features)

In [3]:
X[:,0]

array([ 0.05889832, -1.03825788, -0.73988584,  1.2483609 ,  1.80396262,
       -0.77941863, -0.59704396, -2.07050305, -0.70195867,  0.59623177])

In [4]:
y

array([-0.38287561, -0.60824638,  0.06082262, -0.25265047,  0.07576821,
       -0.25917986, -1.50436022, -1.05534786,  1.14268561, -1.02838427])

In [5]:
clf = Ridge(alpha = .5, normalize = True)
clf.fit(X, y)
clf.coef_

array([ 0.09169217,  0.41924017, -0.06970058,  0.19146744,  0.06436445])

In [6]:
X[:,0] = X[:,0] * 2
clf = Ridge(alpha = .5, normalize = True)
clf.fit(X, y)
clf.coef_

array([ 0.04584609,  0.41924017, -0.06970058,  0.19146744,  0.06436445])

In [7]:
df = pd.read_csv('prostate.csv')

In [8]:
df

lcavol   lweight  age      lbph  svi       lcp  gleason  pgg45  \
0  -0.579818  2.769459   50 -1.386294    0 -1.386294        6      0   
1  -0.994252  3.319626   58 -1.386294    0 -1.386294        6      0   
2  -0.510826  2.691243   74 -1.386294    0 -1.386294        7     20   
3  -1.203973  3.282789   58 -1.386294    0 -1.386294        6      0   
4   0.751416  3.432373   62 -1.386294    0 -1.386294        6      0   
..       ...       ...  ...       ...  ...       ...      ...    ...   
92  2.830268  3.876396   68 -1.386294    1  1.321756        7     60   
93  3.821004  3.896909   44 -1.386294    1  2.169054        7     40   
94  2.907447  3.396185   52 -1.386294    1  2.463853        7     10   
95  2.882564  3.773910   68  1.558145    1  1.558145        7     80   
96  3.471966  3.974998   68  0.438255    1  2.904165        7     20   

        lpsa train  
0  -0.430783     T  
1  -0.162519     T  
2  -0.162519     T  
3  -0.162519     T  
4   0.371564     T  
..       ...   ...  
92  4.385147     T  
93  4.684443     T  
94  5.143124     F  
95  5.477509     T  
96  5.582932     F  

[97 rows x 10 columns]

In [9]:
train = df[df["train"] =="T"]
test = df[df["train"] =="F"]
train = train.drop(['train'], axis=1)
test = test.drop(['train'], axis=1)

In [10]:
train.shape

(67, 9)

In [11]:
test.shape

(30, 9)

In [12]:
X_train = train.drop(['lpsa'], axis=1).to_numpy()
y_train = train["lpsa"].to_numpy()
X_test = test.drop(['lpsa'], axis=1).to_numpy()
y_test = test["lpsa"].to_numpy()

In [13]:
regr = linear_model.LinearRegression()
regr.fit(X_train, y_train)
y_pred = regr.predict(X_test)
mean_squared_error(y_test, y_pred) * y_test.shape[0]

15.638220165228065

In [21]:
model_bic = LassoLarsIC(criterion='bic')
model_bic.fit(X_train, y_train)
model_bic.coef_

array([0.4514829, 0.3939886, 0.       , 0.       , 0.2213309, 0.       ,
       0.       , 0.       ])

In [19]:
y_pred = model_bic.predict(X_test)
mean_squared_error(y_test, y_pred)

0.47988523866425875

In [20]:
model_aic = LassoLarsIC(criterion='aic')
model_aic.fit(X_train, y_train)
model_aic.coef_

array([0.46651873, 0.51536139, 0.        , 0.09804311, 0.47691541,
       0.        , 0.        , 0.00307424])

In [17]:
y_pred = model_aic.predict(X_test)
mean_squared_error(y_test, y_pred)

0.4593109542555604

In [27]:
clf = linear_model.Lasso(alpha=0.1, normalize = True)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
mean_squared_error(y_test, y_pred)

0.9829276678036044

In [28]:
clf = linear_model.Lasso(alpha=0.01, normalize = True)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
mean_squared_error(y_test, y_pred)

0.4546070255657481

In [29]:
clf = linear_model.Lasso(alpha=0.5, normalize = True)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
mean_squared_error(y_test, y_pred)

1.056733228060382